### PR TITLE
Multi Tenant Support & Template Edit

### LINKED ISSUE #9: Multi-user requirements
Very good job! I have some friends that are located in areas where openai is banned, and I thought if the software had multi-user capabilities, I could make a client that would be easy for them to use.

I wonder if this is in the plan of the roadmap?

### LINKED ISSUE #18: Mini Enhancement link to github repo
Add Link to this github repo in the footer or elsewhere. :)

### LINKED ISSUE #22: Edit templates
From #8

### PR DESCRIPTION
**Pull request by jimzer**
This PR fixes #22 and fixes #9 and fixes #18.

# Multi-User Support

https://user-images.githubusercontent.com/19983429/224799787-bda122f9-48d5-4cc6-a5c8-4c7b023f86f1.mp4

We now support password-less authentication with NextAuth.
You'll need to add an email provider (you can use a Gmail account for a quick and easy setup).
Then envionment variables now contains:
```
DATABASE_URL="file:./db.sqlite"
NEXTAUTH_SECRET=<secret for next auth: use a random strong password>
NEXTAUTH_URL=<the app url, for localhost: http://localhost:3000>

EMAIL_SERVER_HOST=<SMTP server>
EMAIL_SERVER_PORT=<SMTP port>
EMAIL_SERVER_USER=<SMTP user>
EMAIL_SERVER_PASSWORD=<SMTP password>
EMAIL_FROM=<address email used to send emails>

ADMIN_EMAIL=<email of the admin user>
```

You can now share your API Key with multiple users.

The workflow is the following:
1. Add the new variables to the environment variables file
2. Start the app
3. You will be asked to sign in
4. At the beginning, only the email corresponding to the `ADMIN_EMAIL` is allowed to login
5. Enter the email address and you will receive an email with a sign in link
6. Click on the link, you're redirected to the app and you're singed in
7. Now go to `/settings`, open the accounts tab and create a new user
8. Enter the email address
9. Congratulations: your new user can now sign in to the app 🚀

Only the admin now sees the app settings. You will have to set an API key. It will then be shared with all your users. Meaning that every action that needs OpenAI performed by your users will use your API key.

If you would prefer another behavior, let me know.

@DennisTheD we will need to adapt the Docker image to work with these new changes.

# Edit Template

You now have an edit button to edit a template name or content.

### CODE REVIEW

**Comment by DennisTheD** [comment]
The Docker fix is an easy one. In my environment there are currently two things:
 1. The new folder "types" is not listed inside the .dockerignore
 2. The startup.sh needs to be converted to unix line endings (e.g. using `dos2unix startup.sh`). This is probably only required if you build on a Windows machine.

I was wondering if it might be a good idea to implement the user management as an optional feature. While I can imagine many use cases, it's probably not a requirement for users just playing around with some prompts inside their local network (like me 😄). With the current changes, you can not simply spin up a docker container without configuring lots of options and setting up an SMTP-Server. 
What do you think about this?

**Comment by jimzer** [comment]
Thanks for the quick feedback 👍🏽.

You have a good point.
Users might not want to use the multi-account support.

I will think about a way to make it opt-in.

I won't merge this PR until it's solved. But it might require quite some refactoring to handle both scenarios properly.
I will keep you updated.

**Comment by SaschMie** [comment]
Actual this is not working, because its not like in the video. It shows not only a email field, instead a password field too and no one can login now.

**Comment by thomasWos** [comment]
Agree, I'm stuck on the sign in page

**Comment by SaschMie** [comment]
It seems u need a variable ADMIN_PASSWORD and put your PW in there. This solved it for me,

**Pull request merged**
