### PR TITLE
Dockerize the app

### PR DESCRIPTION
**Pull request by DennisTheD**
Added a Dockerfile to dockerize the app
Added an action workflow to automatically build and push a docker image.

### CODE REVIEW

**Comment by DennisTheD** [comment]
In order to use the automatic build and push action, you need to set up two repository secrets: DOCKER_USERNAME and DOCKER_PASSWORD. 
I have never used repository secrets inside a public repo. Since the workflow is only manually triggered or when pushing to main, the secrets should be safe in there. But I am not an expert, so you might prefer to make a quick google search on this topic before placing a password in here ;)
Right now, the database is created and migrated at build time. This might work for now, but should be changed in future versions in order to allow easy upgrades of the container when releasing new versions.
You can take a look at the resulting image at: [https://hub.docker.com/r/dennisdoering/ai-chat-app](https://hub.docker.com/r/dennisdoering/ai-chat-app).

**Review by matthewcmorgan — COMMENTED** [review]
LGTM - I l ike this change, good clean action, minimal container, copied over from build.

**Comment by jimzer** [comment]
@DennisTheD Wow great work!

I'm checking it right now.
I will merge it soon.
Thanks for setting up the action to build and publish on docker too! 
I will double-check the credentials and add the necessary configuration.

That is a good point about database migration. We need to think about the best way to set it up for continuous updates with minimal friction.

Feel free to propose solutions :)

**Comment by DennisTheD** [comment]
@jimzer Thank you ;) 
I think the database migration problem is already solved with my last commit. Sorry, I did not update my last comment about this topic. The database gets created/migrated at startup during the execution of the docker entry script "startup.sh". That's why I needed to move the prisma dependency from dev to runtime.

**Review by jimzer — APPROVED** [review]

**Comment by jimzer** [comment]
@DennisTheD Oh, I see it makes sense 👍🏽.
We are on a good track. 
The app just got even easier to use thanks to this PR.
I'm merging it right now and setting up the config for docker.

**Comment by jimzer** [comment]
@DennisTheD  I'm happy to tell you that it worked!

I deployed the image on Google Cloud Run as a test. It worked perfectly.

Congrats again for the good work! 

We have a ready Docker image and a workflow to push it in the hub automatically 🚀

**Pull request merged**
