### PR TITLE
added a simple docker based solution

### PR DESCRIPTION
**Pull request by karlkurzer**
Added a simple Dockerfile to get it running :-)

### CODE REVIEW

**Comment by hydazz** [comment]
how big is the resulting docker image without cleaning up node...

**Comment by karlkurzer** [comment]
The resulting image is about 2.9 GB

**Comment by hydazz** [comment]
npm prune --omit=dev --omit=optional && \
npm cache clean --force

**Comment by hydazz** [comment]
Edit the source (local repo) and rebuild the image of one is to develop, either way nobody's going to do any "developing" from within the docker image, its best to recreate it.

**Comment by karlkurzer** [comment]
> npm prune --omit=dev --omit=optional && npm cache clean --force

no change in image size

**Comment by hydazz** [comment]
yarn cache clean*

**Comment by karlkurzer** [comment]
> yarn cache clean*

no change in image size

**Comment by hydazz** [comment]
🤔 https://github.com/imagegenius/docker-ai-chat-app/blob/main/Dockerfile#L28-L32

This image is only 400mb

perhaps
```
  rm -rf \
    /tmp/* \
    /root/.npm \
    /root/.cache
```

**Comment by jimzer** [comment]
Hey @karlkurzer :)
Thanks for contributing! 
The Docker image will simplify the setup 🔥.

Do you want to try the `rm` trick from @hydazz before we merge?

**Comment by hydazz** [comment]
yarn >> npm >> `npm prune --omit=dev --omit=optional`

**Comment by DennisTheD** [comment]
> yarn >> npm >> `npm prune --omit=dev --omit=optional`

Great idea! I updated my fork and gave it a try. Combined with the multi-stage build, I ended up with an image size of 481M, while still making use of the maintained node:lts-alpine image.
If you like, I can provide you with another pull request. Alternatively, you might simply want to copy my Dockerfile?
I also could implement a github action to automatically create the image after every update in this repo and push it to the Docker hub. This would simplify the setup even further. What do you think about this?

**Comment by karlkurzer** [comment]
@DennisTheD I think the proposal with the github action makes most sense :-), please feel free to create a new PR, and I'll close this one!

**Comment by hydazz** [comment]
@DennisTheD well I mean using npm rather than yarn for everything:
```
  npm install && \
  npm ci && \
  npm run build && \
  npm prune --omit=dev --omit=optional && \
  npm cache clean --force && \
```
this removes the need for yarn completely and makes the image tiny

btw `prisma migrate deploy` either by `yarn` or `npx` needs to be ran as a init script, as this initializes the database and if it is done in the dockerfile then you will get errors about tables not existing.

**Comment by hydazz** [comment]
Just use alpine as the base and the only package that is needed is npm

**Pull request closed without merging**
